INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Telha cerâmica tipo francesa','Dimensões aproximadas de 41cm Rendimento: 17 UN/M2',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,463,2,2000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Telha de fibrocimento sem amianto','Dimensões aproximadas 2,44 m x 1,10 m , espessura de 6 mm',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,464,2,1400,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Telha ondulada translúcida em polipropileno                                         Dimensões aproximadas 2,44m x1,10m','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,465,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Telha Cerâmica tipo Colonial ','Dimensões aproximadas 48cmX20cm, de espessura 15cm',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,466,2,1500,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Telha Cerâmica tipo Romana','Dimensões aproximadas 40cm x 21cm x 15 cm',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,467,2,2000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Telha Cerâmica tipo Paulistinha','Dimensões aproximadas 16 cm x 41 cm',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,468,2,1500,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Telha ondulada de fibrocimento','Dimensões 2,44 m x 0,50 m x 4 mm',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,469,2,1000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Telhas Cerâmica Paulista plan (capa e canal)','Dimensões aproximadas comprimento útil 40 cm x largura da bica 17 cm x largura útil 19 cm',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,470,2,1000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Telha tipo Kalheta de fibrocimento 8mm com 3,00m de comprimento','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,471,2,500,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,17,'Forro em régua de PVC 200mm - Inclusive perfis de fixação e acabamento','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,472,2,10000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Rufo em chapa de aço galvanizado n.24 - corte 33cm  com 3,00m de comprimento','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,473,2,1000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Cumeeira de cerâmica colonial medindo 41cm x 21 cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,474,2,500,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Calha Metálica material: Aço Galvanizado, comprimento: 3,0m, largura: 40cm e profundidade: 25cm.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,475,2,1000,NOW(),NOW());
