INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Acabamento Hidra 4.900 C.Max','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,152,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Adaptador C.R Soldável Curto 4" ( 110"mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,153,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Adaptador C.R Soldável Curto 1.1/4" ( 40"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,154,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Adaptador C.R Soldável Curto 2" ( 60"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,155,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Adaptador C.R Soldável Curto 2.1/2" ( 75"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,156,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Adaptador C.R Soldável Curto 3" ( 85"mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,157,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Adaptador PVC Rig. com Rosca e Flange 2 ( 60"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,158,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Adaptador C.R Soldável Curto 1/2 (20mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,159,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Adesivo a Base de Resina Epóxi 100gr.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,160,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Adesivo / P.V. C frasco com 175 gr.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,161,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Adesivo plástico c/ catalisador PVC 400 gr.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,162,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Anel p/ vedação de borracha 40mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,163,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Anel p/ vedação de borracha 50mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,164,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Kit Vaso Sanitário Caixa Acoplada e Assento Branca','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,165,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Barra de tubo PVC Água 20 mm² 1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,166,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Barra de tubo PVC Água 2”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,167,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Barra de tubo PVC Água 75 mm² 2.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,168,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Barra de tubo PVC Água 85 mm² 3"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,169,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Barra de tubo PVC Água 110 mm² 4"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,170,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Barra de tubo PVC Esgoto 40 mm² 1.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,171,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Barra de tubo PVC Esgoto 50 mm² 2"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,172,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Barra de tubo PVC Esgoto 75 mm² 3”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,173,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Barra de tubo PVC Esgoto 100 mm² 4”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,174,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Barra de tubo PVC Esgoto 150 mm² 6"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,175,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bengala de PVC 1,60 mts. 50 mm² 1.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,176,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bóia p/ caixa dágua 1.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,177,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bolsa em PVC 4"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,178,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bolsa flexível de polietileno 1.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,179,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Braço prolongador de chuveiro 30cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,180,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Braço prolongador de chuveiro 40cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,181,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 1" x 3/4" curta ( 32"x 25"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,182,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 3/4" x 1/2" curta ( 25"x 20"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,183,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 1" x 1/2" longa ( 32 x 20 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,184,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de redução 2” x 1” longa ( 60 x 50mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,185,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 1.1/2" x 1.1/4 curta ( 50"x 40"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,186,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 1.1/2" x 3/4  ( 50"x 25"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,187,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 2" x 1" ( 60"x 32"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,188,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 2" x 1.1/2" curta ( 60"x 50"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,189,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 2"x 3/4" ( 60"x 25"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,190,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 1 x ¾ (32” x 25”mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,191,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 3" x 2.1/2"  ( 85"x 75"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,192,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 3" X 2.1/2" curta (85" x 75"mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,193,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução 4" X 2.1/2" curta (110" x 75"mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,194,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bucha de Redução R.C longa 4" x 2" ( 110"x 60"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,195,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Caixa d’água em polietileno com tampa 1000 Litros','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,196,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Caixa de descarga com engate d/ fixação','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,197,2,70,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC Rigido Soldavel 3/4" água ( 25"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,198,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC Rigido Soldavel 2.1/2" água ( 75"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,199,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC Rigido Soldavel 1.1/4" água ( 40"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,200,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC esgoto 1.1/2 ( 40"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,201,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC esgoto 2" ( 50"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,202,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC esgoto 3" ( 75"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,203,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC esgoto 4" ( 100"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,204,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC Rigido Soldavel 2" água ( 60"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,205,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC Rigido Soldavel 1/2" água ( 20"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,206,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC Rigido Soldavel 1" água ( 32"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,207,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC Rigido Soldável 3" água ( 85"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,208,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC Rigido Soldavel 4" água ( 110"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,209,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cap PVC Rigido Soldavel 1.1/2" água ( 50"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,210,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo Azul de 90 água C.R 3/4" ( 25 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,211,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo Azul Redução 1" x 3/4 C.R','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,212,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo L.R (25 x ½)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,213,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo L.R (25 x ¾)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,214,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo L.R 32 x ¾','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,215,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo d/ Redução 3/4 x 1/2 (25 x 20 mm²)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,216,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo d/ Redução 1 x 3/4 (32 x 25 mm²)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,217,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45 PVC L R água 1" ( 32" mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,218,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45 PVC rigido Soldável 1/2 (20mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,219,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45º PVC água 4" ( 110" mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,220,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45º PVC esgoto 1.1/2" ( 40"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,221,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45 PVC esgoto 2” ( 50mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,222,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45º PVC esgoto 3" ( 75"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,223,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45º PVC esgoto 4" ( 100"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,224,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45º PVC Rigido Soldável 2.1/2" ( 75"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,225,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45º PVC Rigido Soldável de 1" ( 32"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,226,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45º PVC Rigido Soldável de 1.1/2" ( 50"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,227,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45º PVC Rigido Soldável de 2" ( 60"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,228,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45º PVC Rigido Soldável de 3" ( 85"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,229,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 45º PVC Rigido Soldável de 3/4" ( 25" mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,230,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90 PVC esgoto 1.1/2 ( 40 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,231,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90º PVC esgoto 2" ( 50mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,232,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90 PVC esgoto 3" ( 75 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,233,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90 PVC esgoto 4" ( 100 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,234,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90 PVC esgoto 6" ( 150 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,235,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90 PVC Rigido Soldável de 1.1/2" ( 50 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,236,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90 PVC Rigido Soldável de 1/2" ( 20 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,237,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90 PVC Rigido Soldável de 2" ( 60 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,238,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90 PVC Rigido Soldável de 2.1/2" ( 75 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,239,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90 PVC Rigido Soldável de 3" ( 85 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,240,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90 Rigido soldável azul 1/2" ( 20 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,241,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de 90º Rígido soldavel de 1.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,242,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Cotovelo de Red. Azul água 3/4" x 1/2" C.R( 25 x 20 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,243,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 45 PVC esgoto 1.1/2" ( 40"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,244,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 45 PVC esgoto 4" ( 100"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,245,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 45º PVC água 1" ( longa ) ( 32"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,246,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 45º PVC água 1.1/2" longa ( 50"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,247,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 45º PVC água 2” (60 mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,248,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 45º PVC água 3/4" ( longa ) ( 25"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,249,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 90 PVC água 1" (longa) ( 32" mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,250,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 90 PVC água 1.1/2" ( longa ) ( 50 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,251,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 90 PVC água 1/2  ( 20 mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,252,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 90 PVC água 2" (longa) ( 60"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,253,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 90 PVC água 3/4" ( 25"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,254,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 90 PVC esgoto (50"mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,255,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 90 PVC esgoto ( 50"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,256,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 90 PVC esgoto 3" ( longa ) ( 75 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,257,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 90 PVC esgoto 3" ( curta ) ( 75 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,258,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Curva de 90º PVC soldável branca (curta) 4”( 100 mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,259,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Engate flexível de lavatório 1/2 30 cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,260,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Engate flexível de lavatório 1/2 40 cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,261,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Fita teflon veda rosca 18 mm ¾ (rolo c/ 50 metros)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,262,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Grelha em PVC p/ caixa sifonada redonda 6” (150 mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,263,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Joelho 90º c/ anel esgoto série normal 40 mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,264,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Joelho 90º c/ anel esgoto série normal 50 mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,265,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Junção de redução 3” x 2” Esgoto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,266,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Junção simples PVC esgoto 2” x 2”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,267,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Junção simples PVC esgoto 3” x 3” (75mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,268,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Junção simples PVC esgoto 4” x 3” ( 100 x 75 mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,269,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Junção simples PVC esgoto 4” x 4” (100 x 100 mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,270,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Lavatório c/ coluna branco (7 litros)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,271,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Lavatório sem coluna branco (5 litros)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,272,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Lavatório sem coluna branco (7 litros)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,273,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva Azul água C.R ¾ ( 25”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,274,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva Azul de redução PVC água C.R ¾ x ½','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,275,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva Azul de redução PVC água 1” x ¾” ( 32” x 25” mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,276,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de passagem Esgoto 100 x 4','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,277,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de passagem de 2”  ( 60”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,278,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de passagem Esgoto 3”  ( 75” mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,279,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC água lisa 1.1/2” ( 50” mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,280,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC água lisa 1.1/4” ( 40”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,281,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC água lisa ½” ( 20”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,282,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC água lisa 2” ( 60”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,283,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC água lisa 2.1/2”  ( 75”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,284,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC água lisa 3” ( 85”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,285,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC esgoto 1.1/2” ( 40”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,286,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC esgoto 2” ( 60” mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,287,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC esgoto 3” (75” mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,288,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC esgoto 4”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,289,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC L R água 1”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,290,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC L R água ½','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,291,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC L R água ¾”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,292,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC L R ¾” x ½ (25 x 20mm²)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,293,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC Rígido C.R 1.1/2 Esgoto (50 mm² )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,294,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC Rígido Soldável Azul ½ (20mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,295,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de PVC soldável 4”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,296,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva PVC rígido roscável 3/4 (25 mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,297,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de red. PVC água 1” x ¾” ( 32” x 25”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,298,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de red. PVC água 2” x 1.1/2 ( 60” x 50”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,299,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Luva de red. PVC água 3” x 2.1/2 (85” x 75” mm) Longa','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,300,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Massa plástica c/ catalizador','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,301,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Niple PVC rígido roscavel 1.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,302,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Plug PVC rígido roscavel 1”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,303,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Plug PVC rígido roscavel 1.1/2”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,304,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Plug PVC ígido roscavel ½”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,305,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Plug PVC rígido roscavel 3”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,306,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Porta grelha em PVC p/ caixa sifonada 100 mm 4”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,307,2,70,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Porta grelha em PVC p/ caixa sifonada 150 mm 6”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,308,2,70,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Porta grelha em PVC p/ caixa sifonada (Completa) 100 mm 4”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,309,2,70,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Porta grelha em PVC p/ caixa sifonada (Completa)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,310,2,70,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Prolongador de P.V.C ½ x ¾','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,311,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Prolongador em latão ½','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,312,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Prolongador em latão ¾','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,313,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Ralo sifonado 10 x 10 cm ( 4” ) esgoto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,314,2,70,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Ralo sifonado 6” esgoto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,315,2,70,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Ralo seco 10 cm ( 4” )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,316,2,70,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro de Esfera latão 1”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,317,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro de Esfera latão 1.1/2”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,318,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro de Esfera latão 2”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,319,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro de Esfera latão 4”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,320,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro gaveta 1” bruto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,321,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro gaveta 1.1/2” bruto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,322,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro gaveta 1.1/2” com acabamento','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,323,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro gaveta 1.1/4” bruto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,324,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro gaveta 2” bruto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,325,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro gaveta 2” com acabamento','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,326,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro gaveta 2.1/2” bruto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,327,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro gaveta 3” bruto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,328,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro gaveta ¾ bruto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,329,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro gaveta ¾” com acabamento','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,330,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro pressão ¾” bruto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,331,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Registro pressão com acabamento ¾”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,332,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Reparo para válvula de descarga Docol','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,333,2,400,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Sifão metal cromado copinho 1.1/2 x ½','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,334,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Sifão metal cromado copinho 1.1/2 x 2”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,335,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Sifão PVC pia e lavatório 2” x 2”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,336,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Sifão PVC pia e lavatório 1 x 1.1/2”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,337,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Sifão regulável 1.1/2 x 1.1/4 Universal','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,338,2,400,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Bolsa spud 1 ½”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,339,2,400,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Tapa furo T soldável azul (20mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,340,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Tapa furo T soldável azul (25mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,341,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Tapa furo T soldável azul (50mm)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,342,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Tampo e Assento para Adulto Branca','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,343,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te Azul d/ Redução3/4 x ½ água','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,344,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te 90º PVC rígido soldável (L / R azul ¾”(25”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,345,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te 90º PVC rígido soldável (L / R azul ½” (20”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,346,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC água com Redução 1.1/2 x 1” ( 50” x 32” mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,347,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC água com Redução 1.1/2 x ½” ( 50” x 20” mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,348,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC água com Redução 1.1/2 x ¾” ( 50” x 25” mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,349,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC água com Redução 3” x 2” ( 85”x 60”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,350,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC água com Redução 3” x 2.1/2” ( 85”x 75” mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,351,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC água com Redução 3” x ¾” ( 85 x 25 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,352,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC água com Redução ¾” x ½” ( 25” x 20” mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,353,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC água com Redução 4” x 3” ( 110 X 85 mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,354,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC de Redução Esgoto 3” x 2” ( 75 x 50mm² )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,355,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC de Redução Esgoto 4” x 2” ( 100 x 50mm² )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,356,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC de Redução Esgoto 4” x 3”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,357,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC esgoto 6”x 6”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,358,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC Rigido Soldável 1.1/2” ( 50”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,359,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC Rigido Soldável ½” ( 20”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,360,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC Rigido Soldável 2” ( 60”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,361,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC Rigido Soldável 2.1/2” ( 75”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,362,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC Rigido Soldável 3” ( 85”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,363,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te PVC Rigido Soldável 4” ( 110”mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,364,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te Rigido Soldável Esgoto 2” ( 50 mm² )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,365,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te Rígido Soldável Esgoto 3” ( 75mm² )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,366,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te Rígido Soldável Esgoto 4” ( 100mm² )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,367,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Te Rígido Soldável Esgoto 1.1/2” ( 40 mm² )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,368,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Torneira p/ lavatório em latão cromado ½','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,369,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Torneira p/ pia em latão cromado ½ x ¾” ( 22cm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,370,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Torneira para Bebedouro tipo copo cromado 7/16 jato','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,371,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Torneira de pressão para Bebedouro (Grande)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,372,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Torneira p/ jardim em latão cromado ½ x ¾','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,373,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Tubo p/ ligação de bacia (vaso sanitário) ajustavél','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,374,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Tubo p/ ligação de bacia (vaso sanitário) cromado','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,375,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'União de “PVC Rígido Soldável 1/2” (20”mm)”.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,376,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'União de PVC Rígido Soldável 2" ( 60" mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,377,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'União de PVC Rígido Soldável 3/4" ( 25"mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,378,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'União de PVC Rígido Soldável 4" ( 110" mm )','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,379,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Válvula de Descarga 1.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,380,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Válvula de descarga Hidra 1.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,381,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Válvula p/ lavatório em PVC 1”','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,382,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Válvula p/ lavatório em PVC 1.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,383,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Válvula de pia com ladrão 32mm x 60 mm 1" x 2"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,384,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Válvula de pia cromada 32mm² x 60mm² 1" x 2"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,385,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Válvula de Tanque cromado 1.1/2 x 2.1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,386,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Vaselina sólida 90gr.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,387,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Vedante para Torneira 1"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,388,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Vedante para torneira 3/4','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,389,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Vedante para Torneira 1/2"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,390,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Anel de Vedação Borracha Esgoto 200mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,391,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Anel de Vedação Borracha Esgoto 150mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,392,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Anel de Vedação Borracha Esgoto 100mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,393,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Anel de Vedação Borracha Esgoto 75mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,394,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Anel de Vedação Borracha Esgoto 50mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,395,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,3,8,'Anel de Vedação Borracha Esgoto 40mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,396,2,300,NOW(),NOW());
