INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Sarrafo Pinus 5 x 300 cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,112,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Sarrafo Pinus 10 x 300 cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,113,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Sarrafo Pinus 15 x 300 cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,114,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,10,'Prego de aço 18 x 27','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,115,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,10,'Prego de aço 15 x 15','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,116,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,10,'Prego de aço 17 x 21','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,117,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Chapa plastificado 220 x 110 x 10 cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,118,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Chapa plastificado 220 x 112 x 12 cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,119,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Chapa compesada resinado tipo Madeirite 5mm 220 x 110 cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,120,2,80,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Chapa compesada resinado tipo Madeirite 10mm 220 x 110 cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,121,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,9,'Porta','Espessura: 3,50 CM com batentes inclusos',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,122,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,9,'Porta','Espessura: 3,50 CM com batentes inclusos',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,123,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Placa Compensado de Virola','Espessura: 10 MM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,124,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Placa Compensado','Espessura: 15 MM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,125,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Lixa','Aplicação: Marcenaria',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,126,2,800,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Lixa','Aplicação: Marcenaria',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,127,2,800,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Lixa','Aplicação: Marcenaria',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,128,2,800,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,9,'Lixa','Aplicação: Marcenaria',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,129,2,800,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Rodapé de Porta/guarnição','Espessura: 15 MM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,130,2,180,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Ripa','Espessura: 1,00 CM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,131,2,2000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tábua Madeira','Comprimento: 4,00M',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,132,2,3000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Sarrafo','Espessura: 2,5 CM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,133,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Sarrafo','Largura: 10 CM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,134,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Lixa','Aplicação: Marcenaria',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,135,2,800,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Lixa','Aplicação: Marcenaria',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,136,2,800,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Lixa','Aplicação: Marcenaria',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,137,2,800,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Lixa','Aplicação: Marcenaria',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,138,2,800,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,9,'Rodapé de Porta/guarnição','Espessura: 15 MM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,139,2,180,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Ripa','Espessura: 1,00 CM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,140,2,2000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tábua Madeira','Comprimento: 4,00M',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,141,2,3000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,4,'Caibro','Largura: 6 CM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,142,2,1000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,4,'Madeira Construção','Formato: Pontalete',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,143,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Sarrafo','Espessura: 2,5 CM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,144,2,600,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,3,'Sarrafo','Largura: 10 CM',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,145,2,3000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Madeira Construção','Características Adicionais: Sem Tratamento',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,146,2,500,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Madeira Construção','Características Adicionais: Sem Tratamento',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,147,2,400,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Madeira Construção','Características Adicionais: Sem Tratamento',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,148,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Madeira Construção','Características Adicionais: Sem Tratamento',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,149,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Madeira Construção','Características Adicionais: Sem Tratamento',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,150,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Madeira Construção','Características Adicionais: Aparelhada e lixada',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,151,2,100,NOW(),NOW());
