INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,12,'Tinta para piso na cor Concreto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,397,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,12,'Tinta para piso na cor Amarelo','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,398,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,12,'Tinta para piso na cor Cinza','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,399,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,12,'Tinta para piso na cor Azul','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,400,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,12,'Tinta para piso na cor Vermelho','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,401,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,12,'Tinta para piso na cor Verde','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,402,2,500,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,12,'Tinta Latex na cor Branco','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,403,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,11,'Zarcão na cor Laranja','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,404,2,150,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,11,'Zarcão na cor grafite','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,405,2,150,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Trincha,pincel Simples,2 1/2"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,406,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Trincha, pincel simples 3/4','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,407,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Rolo de Lã de Carneiro  23cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,408,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Brocha para Pintura, Fios Em Polipropileno, Cabo Em Polipropileno','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,409,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Alongador para Rolo de Pintura 3,0m','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,410,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Cabo/suporte para Rolo de Pintura,aco Galvanizado,pvc,23cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,411,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Caçamba para pintura - 15 L','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,412,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,15,'Gesso','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,413,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,12,'Massa Corrida PVA','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,414,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,12,'Massa Corrida Acrílica','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,415,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,11,'Selador Acrílico','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,416,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,11,'Fundo Preparador','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,417,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,13,'Removedor de tinta (Pintoff) - 1L','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,418,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Fita Crepe 18mm x 50m','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,419,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Fita Crepe 24mm x 50m','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,420,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Fita Crepe 48mm x 50m','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,421,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Espátula de aço inox de 6cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,422,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Espátula de aço inox de 7,5cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,423,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Espátula de aço inox de 10cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,424,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Espátula de aço inox de 12cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,425,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,14,'Thinner','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,426,2,500,NOW(),NOW());
