INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tubo galvanizado 2x1/8 redondo','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,427,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tubo galvanizado 1x1/8 redondo','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,428,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tubo 150x60x4','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,429,2,35,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Ferro chato 40x10','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,430,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Ferro chato 25x2.65','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,431,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Cantoneira 3/4','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,432,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'cantoneira 1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,433,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Cantoneira 1x1/8','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,434,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Cantoneira 2x1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,435,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Perfil T','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,436,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Ferro chato 1/2x1/8','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,437,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Gonzo n° 3','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,438,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Gonzo n° 2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,439,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Gonzo n° 5','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,440,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Perfil U 2"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,441,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Perfil U 3"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,442,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Chapa 265 Lisa','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,443,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Chapa 265 furada','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,444,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tubo 30x30x1.50','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,445,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,3,'Tela para alambrado','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,446,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,3,'Tela de arame para gradil','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,447,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tarugo 30x30','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,448,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tarugo 20x20','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,449,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tubo redondo 200mm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,450,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tubo 50x50x2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,451,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Tubo 50x30x2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,452,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Perfil de batente','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,453,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Vegalhão 1/2 liso','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,454,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Vegalhão 1" liso','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,455,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Rolamento 1"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,456,2,60,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Rolamento 2"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,457,2,60,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,3,'Corrente 8mm gomo 1"','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,458,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,3,'Corrente 6mm gomo 1/2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,459,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Zarção galão 18L','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,460,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,8,'Galvite galão 18L','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,461,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,2,16,'Massa plástica','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,462,2,15,NOW(),NOW());
