INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'5323193 - Cabo Telefonico, Uso Interno, 20 Pares','Cabo Telefonico; Uso Interno; Designacao Usual Ci-50; Com 20 Pares; Material Condutor Em Cobre Eletrolitico Estanhado; Com Diametro de 0,50mm; Com Isolante Em Cloreto de Polivinila (pvc); Material de Cobertura Em Cloreto de Polivinila (pvc); Na Cor Cinza; Blindagem Em Fita Aluminizada, Diâmetro Externo Nominal 12,5 Mm +/- 0,05; Devera Atender a Norma Spt - 235-310-702 (telebras);',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,1,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Bipolar 100A Tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,2,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Bipolar 80A Tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,3,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Bipolar 63A tipo DIN curva C.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,4,2,60,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Bipolar 32A tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,5,2,60,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Bipolar 25A tipo DIN curva C.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,6,2,60,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Bipolar 20A tipo DIN curva C.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,7,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Monopolar 20A Tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,8,2,80,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Monopolar 25A Tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,9,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Monopolar 16A Tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,10,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Monopolar 32A Tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,11,2,80,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Tripolar 100A Tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,12,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Tripolar 80A Tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,13,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Tripolar 32A Tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,14,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Tripolar 50A Tipo DIN curva C','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,15,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Disjuntor Tripolar 63A Tipo DIN curva C .','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,16,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre, Tempera Mole, 2.5mm2, Flexivel, Verde','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,17,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre, Tempera Mole, Classe 5, 2.5mm2, Flexivel, Azul','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,18,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre, 2.5mm2, 450/750v, Flexivel, Preto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,19,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre Flexivel, 2.5mm2, 750 V, Classe 4, Branco','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,20,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre, Flexivel, 2,5mm2, 750v, Vermelho','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,21,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre, 4,0 Mm2, Flexivel, 450/750 V, Vermelho','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,22,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre Flexivel, 4.0mm2, 750 V, Classe 4, Preto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,23,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre Isolado 4mm2 750v                 AZUL','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,24,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre Isolado 4mm2 750v Na Cor Branco','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,25,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre Isolado 4mm2 750v Na Cor Verde','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,26,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico Com Area de Secao de 6mm2 Na Cor Preta','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,27,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre Isolado 6mm2 750v                 AZUL','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,28,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico Com Area de Secao de 6mm2 Na Cor Vermelho','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,29,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico Com Area de Secao de 6mm2 Verde','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,30,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre Flexivel, 10.0mm2, 750 V, Classe 5, Azul','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,31,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico Cobre, 10mm2, Anti-chama, 450/750v, Flexivel, Preta.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,32,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico de Cobre Flexivel, 10.0mm2, 750 V, Classe 5, Verde','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,33,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico, Cobre, 16mm, Classe 4, 450/750 V, Flexivel, Verde','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,34,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico, Cobre, 16mm, Classe 4, 450/750 V, Flexivel, Preto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,35,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico, Cobre, 16mm, Classe 4, 450/750 V, Flexivel, Azul','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,36,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,5,'Cabo Eletrico, Cobre, 16mm, Classe 4, 450/750 V, Flexivel, Vermelho','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,37,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,3,'Cabo Eletrico de Cobre Isolado 25mm2 750v                 AZUL','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,38,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,3,'Cabo Eletrico de Cobre Isolado 25mm2 750v                 PRETO','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,39,2,400,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,6,'Fita Isolante, Autofusão, de Epr, Nao Perecivel, Isolação 69kv, 130ºc','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,40,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,6,'Fita Isolante Adesivo Em Pvc Rolo 19mm x 20m Na Cor Preta','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,41,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Fusivel Eletrico, Nh 1, 125 A, 500 V, Corpo Porcelana, Ação Retardada','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,42,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Soquete para Lampada Incandescente,porcelana,e-27,250v,4a','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,43,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Quadro Distribuicao Eletrica Geral, 6 a 8 Disjuntores, Padrao Nema,pvc','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,44,2,60,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,8,'Caixa de Sobrepor, Medindo 4x2", Sistema X, Fabricada Em Pvc Rigido','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,45,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,7,'Eletroduto Corrugado,em Pvc,diam.1/2polegada,antichama,cor Amarela','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,46,2,5,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Curva longa de PVC preto 1.1/4 Pol. Com rosca Bsp','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,47,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Luva para eletroduto de PVC roscavel 1.1/4 Pol. Preto','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,48,2,40,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,7,'Eletroduto Corrugado, Em Pvc, 3/4 Pol, Antichama','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,49,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,7,'Eletroduto Corrugado, Em Pvc, 1 Pol, Antichama','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,50,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,6,'Eletroduto Corrugado, Em Pvc, 1 1/2 Polegada, Na Cor Preta','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,51,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Condulete Galvanizado 3/4 tipo múltiplo X , c/ tampa (sem código)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,52,2,150,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Caixa retangular de embutir, 4x2, PVC,  Amarela','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,53,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Caixa retangular de embutir, 4x4, PVC,  Amarela','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,54,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Lâmpada LED Tubular T8 9w/10w Bivolt 6500k, 60cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,55,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Lâmpada LED Tubular T8 18w/20w Bivolt 6500k, 120cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,56,2,400,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Refletor / Projetor LED, 50W, Luz branca-6000K , IP-65, bivolt,  10x14x3cm, em aluminio preto com vidro, com suporte para parede/teto.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,57,2,60,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Lâmpada Led Bulbo E-27  12W  6500K','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,58,2,500,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Lampada de Led 20W','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,59,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Paflon Plástico branco redondo com bocal de porcelana E-27','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,60,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Luminaria, Corpo Em Chapa de Aço, Cor Branca, Base G13 para 2 Lâmpadas','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,61,2,60,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Luminária Sobrepor tubular 2 lamp. Led 20W 120cm','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,62,2,80,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Luminaria de Led, Refletor Com Dissipador, 3 Modulos, 150w','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,63,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Luminaria de Led, Refletor Com Dissipador, 3 Modulos, 80w','(SEM CÓDIGO)',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,64,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Luminária para iluminação pública Led 60 W, bivolt- IP66 - Tecnowatt modelo TW 4003220TAU - 61W - 4000 Kelvin (SEM CÓDIGO)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,65,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Luminária  para poste, iluminação pública, Led 50 W, 220 V, IP 66, Trópico, padrão PMSP (SEM CÓDIGO)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,66,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Soquete para Lampada Fluorescente,anti-vibratorio,engate Rapido,g13','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,67,2,400,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Caixa de Sobrepor, Marfim, C. Tomada P/ Telefone 4 Contatos + Rj11','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,68,2,20,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Tomada Eletrica, Sobrepor, Quadrado, 20a 250v','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,69,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conjunto Interruptor Sobrepor, simples 1 tecla, 10A ,, branco..','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,70,2,80,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Tomada Eletrica, Termoplastico, Embutir Dupla, 2 Polos + Terra','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,71,2,150,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conjunto Tomada Eletrica, Termoplastico, Embutir simples, 2 Polos + Terra 10A PADRÃO BRASILEIRO, 4x2, branco, com espelho.','(SEM CÓDIGO)',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,72,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conjunto Tomada Eletrica, Termoplastico, Embutir simples, 2 Polos + Terra 20A PADRÃO BRASILEIRO, 4x2, branco, com espelho.','(SEM CÓDIGO)',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,73,2,150,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Tomada Eletrica, Termoplastico, Embutir simples, 2 Polos + Terra 10A PADRÃO BRASILEIRO','220V (SEM CÓDIGO)',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,74,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Tomada Eletrica, Termoplastico, Embutir simples, 2 Polos + Terra 20A PADRÃO BRASILEIRO','220V (SEM CÓDIGO)',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,75,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conjunto Interruptor Embutir simples 1 tecla, 10A , 4x2, branco, com espelho.','(SEM CÓDIGO)',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,76,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conjunto Interruptor Embutir simples 1 tecla e tomada 2P+T, 10A , 4x2, branco, com espelho.','(SEM CÓDIGO)',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,77,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conjunto 2 Interruptores Embutir simples 2 teclas, 10A , 4x2, branco, com espelho.','(SEM CÓDIGO)',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,78,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conjunto 2 tomadas 2P+T, 20A , 4x4, branco, com espelho.','(SEM CÓDIGO)',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,79,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Suporte central DTS.1.60, Repume iluminação (SEM CÓDIGO)','',NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Poste de aço galvanizado - 4m altura, diametro de 75mm, afunilando para 60mm,base 200 x 200mm (SEM CÓDIGO)','',NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,2,'Eletroduto,aco,3/4",galvanizado,sem Rosca','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,82,2,60,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Abraçadeira Tipo D com cunha 3/4 (sem código)','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,83,2,300,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Terminal Unidut Reto 3/4 Pol.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,84,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conector Unidut Conico Diametro 3/4 Polegada','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,85,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Terminal para Condutor Eletrico; Tipo Garfo; para Cabo Flexivel 1,5 a 2,5mm2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,86,2,600,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Terminal para Condutor Eletrico; Tipo Olhal; para Cabo Flexivel 1,5 a 2,5mm2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,87,2,600,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Terminal para Condutor Eletrico; Tipo Garfo; para Cabo Flexivel 4 a 6mm2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,88,2,600,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Terminal para condutor Elétrico, Tipo Olhal para cabo flexível 4 a 6mm2 - furo M6','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,89,2,600,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Terminal tubular de compressão para cabo flexivel 10mm2 - furo M6','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,90,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Terminal tubular de compressão para cabo flexivel 16mm2 - furo M8','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,91,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Terminal tubular de compressão para cabo flexivel 25mm2 - furo M10','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,92,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Luva de emenda tubular de compressão para cabo flexivel 25mm2','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,93,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,1,'Canaleta PVC sistema X branca - 20 X 12mm - com divisão - com adesivo','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,94,2,120,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conector de pressão tipo Split Bolt - 16 mm2                       Liga de cobre com cobertura estanhada.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,95,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conector de pressão tipo Split Bolt - 25mm2                       Liga de cobre com cobertura estanhada.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,96,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conector de pressão tipo Split Bolt - 35mm2                       Liga de cobre com cobertura estanhada.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,97,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conector de pressão tipo Split Bolt - 50mm2                       Liga de cobre com cobertura estanhada.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,98,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conector Grampo para haste de aterramento 1/2 " - Latão com parafuso.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,99,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Conector Grampo para haste de aterramento 5/8 " - Latão com parafuso.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,100,2,50,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Haste de aterramento cobreada 5/8" x 2,40m','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,101,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Caixa de inspeção cônica em PVC c/ tampa para aterramento','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,102,2,30,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,3,'Cabo de Alumínio encordoado nu com alma de aço    CAA - 2 AWG (39mm) - para linhas aéreas','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,103,2,1000,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Elo Fusível para redes de distribuição de energia, capacidade 10K, 500mm, 15KV.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,104,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Elo Fusível para redes de distribuição de energia, capacidade 15K, 500mm, 15KV.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,105,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Elo Fusível para redes de distribuição de energia, capacidade 5 K, 500mm, 15KV.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,106,2,100,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,4,'Chave Fusível para redes de distribuição de energia,  15KV / 300A , com porta fusivel e isolador.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,107,2,10,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,3,'Cabo de Alumínio XLPE encapado singelo 1kV - 35mm2 - para redes de distribuição de baixa tensão.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,108,2,500,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,3,'Cabo Elétrico de Cobre PP 3 x 6mm2, Classe 4, 500 V, Flexivel, Preto.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,109,2,200,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,3,'Cabo Elétrico de Cobre PP 3 x 2,5mm2, Classe 4, 500 V, Flexivel, Preto.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,110,2,500,NOW(),NOW());
INSERT INTO items (departamento_id,tipo_item_id,medida_id,nome,descricao,created_at,updated_at)VALUES (3,1,3,'Cabo Elétrico de Cobre PP 3 x 1,5mm2, Classe 4, 500 V, Flexivel, Preto.','',NOW(),NOW());
INSERT INTO inventarios (departamento_id,item_id,local_id,quantidade,created_at,updated_at)VALUES (3,111,2,500,NOW(),NOW());
